version: '3.3'
services:
  fyfill:
    build: .
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.fyfill.tls'
      - 'traefik.http.routers.fyfill.tls.certresolver=letsencryptresolver'
      - 'traefik.http.services.fyfill.loadbalancer.server.port=3000'
      - 'traefik.http.routers.fyfill.rule=Host(`fyfill.ph1p.dev`)'
      - 'traefik.http.routers.fyfill.middlewares=sslheader@docker'
    environment:
      - PORT=3000
      - URL=https://fyfill.ph1p.dev
      - CLIENT_ID=
      - CLIENT_SECRET=
    networks:
      - default
      - proxy

networks:
  proxy:
    external: true
